config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :events do
    resources :videos
    resources :playlists
  end

  resources :contacts, only: [:new, :create]
  resources :videos
  resources :upcomings
  resources :roles
  resources :tags
  resources :playlists

  post 'videos' => 'videos#create'

  get '/admin', to: 'admin#index', as: :admin #=> admin_path
  get '/contact', to: 'content#contact', as: :contact #=> contact_path
  get '/feedback', to: 'content#contact', as: :feedback #=> feedback_path
  get '/stats', to: 'content#stats', as: :stats_page
  get '/about', to: 'content#about', as: :about #=> about_path
  get '/start', to: 'content#start', as: :start #=> start_path
  get '/howto', to: 'content#howto', as: :howto #=> howto_path
  get '/ignites', to: 'events#index', as: :events_page
  get '/:id', to: 'events#show', as: :event_page

  root to: "content#home"

end

app/views/admin/index.html.haml
.container-fluid
  .row
    .col-md-6.col-md-offset-1
      %h1 Ignite Talks admin panel
    .col-md-1.col-md-offset-2
      = link_to howto_path, class: "light btn-edit", :target => "_blank" do
        %i.fa.fa-question-circle.fa-2x.top-15
    .col-md-1
      .btn-group.top-15
        %button{:type => "button", :class => "btn btn-default dropdown-toggle", "data-toggle" => "dropdown"}
          =current_user.name
          %span.caret
        %ul.dropdown-menu
          %li= link_to "Change your password", edit_user_registration_path
          %li= link_to('Logout', destroy_user_session_path, :method => :delete)

/ Tab headings
.container-fluid
  .row
    .col-md-10.col-md-offset-1
      %ul.nav.nav-tabs{:role => "tablist", :id => "admin_tabs"}
        %li.active{:role => "presentation"}
          %a{"aria-controls" => "videos_tab", "data-toggle" => "tab", :href => "#videos_tab", :id => "tab_videos", :role => "tab"} Videos
        %li{:role => "presentation"}
          %a{"aria-controls" => "playlists_tab", "data-toggle" => "tab", :href => "#playlists_tab", :id => "tab_playlists", :role => "tab"} Playlists
        %li{:role => "presentation"}
          %a{"aria-controls" => "events_tab", "data-toggle" => "tab", :href => "#events_tab", :id => "tab_events", :role => "tab"} Ignites
        %li{:role => "presentation"}
          %a{"aria-controls" => "upcomings_tab", "data-toggle" => "tab", :href => "#upcomings_tab", :id => "tab_upcomings", :role => "tab"} Upcoming events
        -if current_user.curator?
          %li{:role => "presentation"}
            %a{"aria-controls" => "tags_tab", "data-toggle" => "tab", :href => "#tags_tab", :id => "tab_tags", :role => "tab"} Video tags
        -if current_user.admin?
          %li{:role => "presentation"}
            %a{"aria-controls" => "users_tab", "data-toggle" => "tab", :href => "#users_tab", :id => "tab_users", :role => "tab"} Users

/ Tab containers
.container-fluid
  .row
    .col-md-10.col-md-offset-1
      .tab-content

        #videos_tab.tab-pane.active{:role => "tabpanel"}
          %h4.top-25
            .btn.btn-default= link_to "Import a new video", new_video_path, {:class => "blackText"}
            .btn.btn-default{"data-target" => "#importPlaylistModal", "data-toggle" => "modal", :type => "button"}
              Import from YouTube playlist

          %h2.top-25 Published videos
          %table#tblVideos{:data => {:source => videos_path(format: :json, status: "published")}}
            %thead
              %tr
                %th Title
                %th Presenter
                %th Event
                %th Uploaded
                %th Featured
                %th Edit
                %th Delete
            %tbody

          %h2.top-25#drafts Draft videos
          %table#tblDraftVideos{:data => {:source => videos_path(format: :json, status: "draft")}}
            %thead
              %tr
                %th Title
                %th Presenter
                %th Event
                %th Uploaded
                %th Featured
                %th Edit
                %th Delete
            %tbody

        #playlists_tab.tab-pane{:role => "tabpanel"}
          %h4.top-25
            .btn.btn-default= link_to "Create a new playlist", new_playlist_path, {:class => "blackText"}
            .btn.btn-default{"data-target" => "#importPlaylistModal", "data-toggle" => "modal", :type => "button"}
              Import from YouTube playlist
          .top-50
            %table#tblPlaylists{:data => {:source => playlists_path(format: :json)}}
              %thead
                %tr
                  %th Name
                  %th Ignite
                  %th Featured
                  %th Listed
                  %th No. videos
                  %th
                  %th
              %tbody

        #tags_tab.tab-pane{:role => "tabpanel"}
          %h4.top-25
            .btn.btn-default= link_to "Create a new tag", new_tag_path, {:class => "blackText"}
          .top-25
            %table#tblTags{:data => {:source => tags_path(format: :json)}}
              %thead
                %tr
                  %th Name
                  %th No. videos
                  %th
                  %th
              %tbody

        #events_tab.tab-pane{:role => "tabpanel"}
          - if can? :create, Event
            %h4.top-25
              .btn.btn-default=link_to "Create a new Ignite", new_event_path, {:class => "blackText"}
          .top-25
            %table#tblEvents{:data => {:source => events_path(format: :json)}}
              %thead
                %tr
                  %th Name
                  %th City
                  %th Country
                  %th URL
                  %th Twitter
                  %th
                  %th
              %tbody

        #upcomings_tab.tab-pane{:role => "tabpanel"}
          %h4.top-25
            .btn.btn-default=link_to "Crete a new upcoming event", new_upcoming_path, {:class => "blackText"}
          .top-25
            %table#tblUpcomings{:data => {:source => upcomings_path(format: :json)}}
              %thead
                %tr
                  %th Event Name
                  %th Ignite
                  %th Date
                  %th
                  %th
              %tbody

        -if current_user.admin?
          #users_tab.tab-pane{:role => "tabpanel"}
            %h4.top-25
              .btn.btn-default=link_to "Add a new User", new_user_path, {:class => "blackText"}
            .top-25
              %table#tblUsers{:data => {:source => users_path(format: :json)}}
                %thead
                  %tr
                    %th Name
                    %th Email
                    %th Admin?
                    %th No. Sign-ins
                    %th
                    %th
                %tbody

/ Import YouTube playlist modal
#importPlaylistModal.modal.fade{"aria-labelledby" => "importPlaylistModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#importPlaylistModalLabel.modal-title Import from YouTube playlist
        %p.top-15
          This function imports a batch of videos from a YouTube playlist. Since YouTube doesn't have the concept of a "presenter",
          the videos are imported with the speaker name listed as "TBA".
        %p
          Once this function has finished, please open the
          =link_to "Videos", "/admin?tabpane=videos#drafts"
          panel on the Admin page and see the Draft Videos section.
        %p Click on each draft video and edit the speaker name (and make any other required edits) before hitting the Publish button to complete the video importing process.
      .modal-body
        .row.top-25
          .col-md-12
            %form
              .row
                .col-md-8
                  .form-group
                    %label{:for => "selPlaylistDropdown"} Import to playlist:
                    %select#selPlaylistDropdown.form-control
                      -@playlists.each do |playlist|
                        %option{:value => [playlist.id,playlist.event.id]}= playlist.name
              .row
                .col-md-8
                  .form-group
                    %label{:for => "txtYouTubePlaylist"} YouTube playlist URL
                    %input#txtYouTubePlaylist.form-control{:placeholder => "eg https://www.youtube.com/playlist?list=abcdefj", :type => "text"}
                .col-md-4
                  .btn.btn-warning.top-25{:type => "submit", :id => "btnImportFromYouTubePlaylist"} Import from YouTube playlist
        .row
          .col-md-12
            #results
      .modal-footer.left
        %button.btn.btn-default#btnDraftVideos=link_to "Go to Draft Videos page", "/admin?tabpane=videos#drafts", {:class => "blackText"}
        %button.btn.btn-default#btnCloseImportPlaylist{"data-dismiss" => "modal", :type => "button"} Close