config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :events do
    resources :videos
    resources :playlists
  end

  resources :contacts, only: [:new, :create]
  resources :videos
  resources :upcomings
  resources :roles
  resources :tags
  resources :playlists

  post 'videos' => 'videos#create'

  get '/admin', to: 'admin#index', as: :admin #=> admin_path
  get '/contact', to: 'content#contact', as: :contact #=> contact_path
  get '/feedback', to: 'content#contact', as: :feedback #=> feedback_path
  get '/stats', to: 'content#stats', as: :stats_page
  get '/about', to: 'content#about', as: :about #=> about_path
  get '/start', to: 'content#start', as: :start #=> start_path
  get '/howto', to: 'content#howto', as: :howto #=> howto_path
  get '/ignites', to: 'events#index', as: :events_page
  get '/:id', to: 'events#show', as: :event_page

  root to: "content#home"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
  has_and_belongs_to_many :events
  has_many :videos, :through => :events
  has_many :upcomings, :through => :events
  has_many :playlists, :through => :events
  has_many :tags
  validates_presence_of :name, :email
  validates_uniqueness_of :email

  before_save :assign_role

  def assign_role
    self.role = Role.find_by name: "regular" if self.role.nil?
  end

  def admin?
    # administrators have full control
    begin
      if self.role.name == "admin"
        return true
      else
        return false
      end
    rescue Exception => e
      return false
    end
  end

  def curator?
    # curators have enhanced ability to create, edit and delete compared
    # to regular users. Admins inherit this functionality
    begin
      if ['admin','curator'].include? self.role.name
        return true
      else
        return false
      end
    rescue Exception => e
      return false
    end
  end

  def regular?
    begin
      if self.role.name == "regular"
        return true
      else
        return false
      end
    rescue Exception => e
      return false
    end
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  validates_presence_of :title, :event, :url, :speaker_name, :description
  validates :url, format: { with: /\/\/www\.youtube\.com\/watch\?v=([a-zA-Z0-9_-]*)/,
    message: "must be in the format http://www.youtube.com/watch?v=VIDEO_ID" }
  validates :speaker_url, :url => {:allow_blank => true}
  validates_uniqueness_of :url
  validates_uniqueness_of :uid
  belongs_to :event
  has_and_belongs_to_many :tags, after_add: :update_video_count, after_remove: :update_video_count
  has_and_belongs_to_many :playlists, after_add: :update_video_count, after_remove: :update_video_count
  searchkick

  #Allow the creation of new tags and playlists during create/edit videos
  attr_accessor :new_tag_name
  attr_accessor :new_playlist_name
  before_update :check_for_new_tags
  before_update :check_for_new_playlist
  
  before_create -> do

    # If the user has entered any new tags as free text, add them to the Tags and Video
    check_for_new_tags

    # If the user has entered any new playlists as free text, add them to the Playlists and Video
    check_for_new_playlist

    # Retrieve the view, like and dislike counts from YouTube before saving the new video
    uid = url.match(/^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i)
    self.uid = uid[2] if uid && uid[2]
    video = Yt::Video.new id: self.uid
    if self.uid.to_s.length != 11
      self.errors.add(:error, ' - YouTube ID is invalid.')
      false
    elsif Video.where(uid: self.uid).any?
      self.errors.add(:error, '- this video has already been added to IgniteTalks.io!')
      false
    else
      begin
        self.likes = video.like_count
        self.dislikes = video.dislike_count
        self.views = video.view_count
        if video.hd?
          self.hd = true
        end
      rescue
        self.likes = 0 ; self.dislikes = 0 ; self.views = 0; self.hd = false
      end
    end
  end

  # Friendly IDs in the URL
  extend FriendlyId
  friendly_id :title, :use => :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end

  def related_videos
    #Find videos which share the same tag(s)

    Tag.where(id: tags.map(&:id)).joins(:videos).flat_map(&:videos).reject{|video| video.id == id}.reject{|video|}.uniq

    #flat_map takes an array or arrays and flattens it
    #reject knocks out the current video from the related list
    #uniq removes duplicates
  end

  def check_for_new_tags
    #If the user has added any new tags as free text, apply them
    if not new_tag_name.blank?
      new_tag_name.split(",").each do |new_tag|
        # Don't bother tagging anything with "ignite"
        new_tag = new_tag.lstrip.rstrip.downcase
        if new_tag.upcase.index("IGNITE") == nil
          if Tag.where(:name => new_tag).count > 0
            @newTag = Tag.where(:name => new_tag)
          else
            @newTag = Tag.create(:name => new_tag)
          end
          if not self.tags.include? @newTag[0]
            self.tags.append(@newTag)
          end
        end
      end
    end
  end

  def check_for_new_playlist
    #If the user has added any a new playlist as free text, apply them
    if not new_playlist_name.blank?
      if Playlist.where(:name => new_playlist_name).count > 0
        @newPlaylist = Playlist.where(:name => new_playlist_name)[0]
      else
        @newPlaylist = Playlist.create(:name => new_playlist_name, :user => self.user, :event => self.event)
      end
      if not self.playlists.map(&:id).include? @newPlaylist.id
        self.playlists.append(@newPlaylist)
        # @newPlaylist.videos.append(self)
      end
    end
  end

  private
    # Keep track of the number of published videos in a playlist or tag
    def update_video_count(model)
      begin
        model.video_count = model.videos.where(status:'published').count
        model.save!
      rescue
        puts "there was a problem updating the published video count"
      end
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource :find_by => :slug, except: [:index, :show]
  before_action :find_video, only: [:show, :edit, :update, :destroy, :update_stats]
  layout 'no_footer', :only => [:new, :edit]
  before_filter :set_rand_cookie
  before_action :update_youtube_stats, only: [:show]
  
  # rescue_from ActiveRecord::RecordNotFound do
  #   flash[:notice] = 'Sorry, that video does not exist'
  #   redirect_to action: :index
  # end
 
  def index
    if params[:query].present?
      # Find videos using elastic search
      @videos = Video.where("status = 'published'").search(params[:query], page: params[:page], :per_page => 16)

    elsif params[:tag].present?
      # Find videos by tag
      @tag = Tag.find_by(name: params[:tag])
      @videos = @tag.videos.where("status = 'published'").paginate(:page => params[:page], :per_page => 16)

    elsif params[:sort].present? and params[:sort] == 'likes' || params[:sort] == 'views'
      # Sort videos baseed on the number of views
      @videos = Video.where("status = 'published'").order("#{params[:sort]} DESC").paginate(:page => params[:page], :per_page => 16)

    elsif params[:uid].present?
      # Check whether this video already exists. This is called when creating a new video, to save the
      # user from wasting time entering details about an existing video.
      # eg: http://localhost:3000/videos.json?uid=AlkKPojdVAk
      @videos = Video.where(:uid => params[:uid]).paginate(:page => params[:page], :per_page => 16)

    else
      # Show videos in random order. Code is from http://nomethoderror.com/blog/2014/02/05/activerecord-random-ordering-with-pagination/
      seed_val = Video.connection.quote(cookies[:rand_seed])
      Video.connection.execute("select setseed(#{seed_val})")
      @videos = Video.where("status = 'published'").order('random()').paginate(:page => params[:page], :per_page => 16)
    end

    # @tags = Tag.where(major: true).order(:name)

    # Respond as JSON, so that this function can be called via AJAX to determine whether a video
    # already exists when creating a new video via http://localhost:3000/videos/new
    respond_to do |format|
      format.html
      if params[:draw].present?
        format.json { render json: VideoDatatable.new(view_context, { user: current_user, role: current_user.role }) }
      else
        format.json { render json: @videos }
      end
    end

  end

  def new
    # If this user can only manage one event, just assign the video to that event
    if current_user.events.count == 1
      @video = Video.new(event: current_user.events.first)
    else
      @video = Video.new
    end
    @tag = Tag.new
  end

  def show
    #Show up to 4 randomly-selected videos which share the same tags. related_videos is calculated in the video.rb model
    @related_videos = @video.related_videos.shuffle[0, 4]
    
    #Customise the Facebook/Twitter sharing content
    @og_title = "IgniteTalks.io" + " | " + @video.title + " by " + @video.speaker_name
    if @video.description.blank?
      @og_description = @video.speaker_name + " speaks at " + @video.event.name
    else
      @og_description = @video.description
    end
    @og_image = "http://img.youtube.com/vi/#{@video.uid}/maxresdefault.jpg"
    @more_videos = Video.all.order("RANDOM()").limit(4)

    respond_to do |format|
      format.html
      format.json { render json: @video }  # respond with the created JSON object
    end

  end

  def edit
  end

  def create
    @video = Video.create(video_params)
    if @video.save
      begin
        # Email the admins to let them know a new video has been added
        User.where(role: Role.where(name: "admin")).each do |user|
          NotifyMailer.new_video_email(user, @video).deliver_now
        end
      rescue
        puts "There was a problem emailing the admins about this video"
      end
      respond_to do |format|
        format.html {
          flash[:notice] = "Video #{@video.title} added successfully."
          redirect_to video_path(@video)
        }
        format.json { render json: @video, status: :created, location: @video }
      end

    else
      respond_to do |format|
        format.html {
          flash[:notice] = @video.errors.full_messages.to_sentence
          render 'new', layout: 'no_footer'
        }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end 
  end

  def update

    if [params[:video][:speaker_name], params[:video][:description]].include? "TBA"
      # Videos which are auto-imported have the status 'draft' with unknown Speaker Name and Description.
      # Don't allow videos to be published until that is amended
      @video.status = 'draft'
      flash[:notice] = "Please check the Speaker Name and Description field before publishing"
      redirect_to edit_video_path(@video)
    else
      # Otherwise, publish the video
      @video.status = 'published'
      if @video.update(video_params)

        # Update the video_count of any playlists and tags which hold this video
        @video.playlists.each do |playlist|
          playlist.video_count = playlist.videos.where(status: "published").count
          playlist.save!
        end
        @video.tags.each do |tag|
          tag.video_count = tag.videos.where(status: "published").count
          tag.save!
        end

        if current_user.curator?
          redirect_to admin_path
        else
          redirect_to @video
        end
      else
        flash[:notice] = @video.errors.full_messages.to_sentence
        render 'edit'
      end
    end
  end


  def destroy
    @video.destroy
    flash[:notice] = "Video #{@video.title} deleted successfully."
    redirect_to admin_path
  end

private

  def video_params
    params.require(:video).permit(:title, :description, :url, :event_id, :status, :speaker_name, :speaker_url, :uid, :featured, :R18, :new_tag_name, :new_playlist_name, playlist_ids: [], tag_ids: [])
  end

  def find_video
    @video = Video.friendly.find(params[:id])
  end

  def set_rand_cookie
    return if cookies[:rand_seed].present?
    cookies[:rand_seed] = {value: rand, expires: Time.now + 900}
  end

  def update_youtube_stats
    #Update the view, like and dislike counts
    unless @video.uid.nil?
      begin
        video = Yt::Video.new id: @video.uid
        @video.views = video.view_count | 0
        @video.likes = video.like_count | 0
        @video.dislikes = video.dislike_count | 0
        @video.save
      rescue Exception => e
        print "YouTube API error"
      end
    end
  end

  def validate_before_publishing
    # Before saving a video, verify it no longer has "TBA"
    if [video_params[:speaker_name], video_params[:description]].include? "TBA"
      @video.status = 'draft'
      flash[:notice] = "Please check the Speaker Name and Description field before publishing"
      redirect_to edit_video_path(@video)
    else
      # Once it's published, ensure that any playlists it's in have the correct video_count
      @video.status = 'published'
    end
  end

end

app/helpers/videos_helper.rb
module VideosHelper

  def embed(youtube_id)
    # Generate the YouTube iframe embed code based on the YouTube ID
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}?hd=1&rel=0&autohide=0&showinfo=0", :allowfullscreen => "allowfullscreen")
  end

  def thumbnail(video, rating_class, max_length)
    # Generate a thumbnail image containing viewing stats, which links to the video
    render 'videos/thumbnail', :video => video, :rating_class => rating_class, :max_length => max_length
  end

  def thumbnail_without_event_name(video, rating_class, max_length)
    # Generate a thumbnail image containing viewing stats, which links to the video
    render 'videos/thumbnail_without_event_name', :video => video, :rating_class => rating_class, :max_length => max_length
  end

end

app/views/videos/_form.html.haml
= simple_form_for(@video, html: { class: 'form' })  do |f|
  .form-group
    -if current_user.curator?
      =f.input :featured, {:label => "Feature this video on the homepage?"}
    -if @video.id
      %h4#videoStatus{"data-video-status" => @video.status}= "Status: #{@video.status}"
    %hr
    / =f.input :uid, input_html: { class: 'hidden' }
    -if @video.status == 'draft'
      .row.hidden
        =f.input :url
    - else
      .row
        .col-md-10#ignite_name
          %label Filmed at:
          -if current_user.curator?
            = f.collection_select :event_id, Event.all.order(:name), :id, :remove_ignite, {:prompt => "Choose the Ignite"}, {:class=>'form-control select'}
          - else
            = f.collection_select :event_id, current_user.events.all.order(:name), :id, :name, {}, {:class=>'form-control select'}
      .row.top-25
        .col-md-10
          =f.input :url, input_html: { class: 'form-control' }, placeholder: "Enter the URL (in the format https://www.youtube.com/watch?v=YOUTUBE_ID)", label: 'Video URL (required)'
        .col-md-2
          .tooltip-wrapper{:data => {:toggle => "tooltip"}, :title => "Enter the URL, then retrieve title and description from YouTube"}
            %btn.btn.btn-warning.top-25#btnYouTubeRetrieve Get info

    .row.details
      .col-md-12
        =f.input :title,  input_html: { class: 'form-control' }, placeholder: "Enter the video's title", label: 'Video title (required)', hint: 'Do not include the speaker name or event name'
        =f.input :description,  input_html: { class: 'form-control', :rows => 5 }, placeholder: "Enter the video's description", label: 'Video description (required)', hint: 'Please enter a 1-2 sentence summary of the talk\'s topics. This will be displayed under the video, and on Facebook/Twitter posts. Do not include the speaker name or event name, or information about the videographer, etc. This section is just for a description of the talk itself'
        =f.input :speaker_name, input_html: { class: 'form-control' }, placeholder: "Enter the speaker's name", label: 'Speaker name (required)'
        =f.input :speaker_url, input_html: { class: 'form-control' }, placeholder: "Enter the speaker's URL (eg Twitter, blog, etc)", label: 'Speaker URL', hint: 'You can optionally provide a link to the speaker\'s blog, Twitter account, etc'
        =f.input :R18, :label => "Is this video suitable for 18+ only?"
        %hr
        %label.top-15 Tags:
        %p= f.collection_check_boxes :tag_ids, Tag.all.order(:name), :id, :name
        =f.input :new_tag_name, input_html: { class: 'form-control' }, placeholder: "Enter new tags (separated with commas)"

    -if not @video.status == 'draft'
      .row.top-25.details
        %hr
        .col-md-10
          %label Add to playlist:
          -if current_user.curator?
            %p= f.collection_check_boxes :playlist_ids, Playlist.all.order(:name), :id, :name
          - else
            %p= f.collection_check_boxes  :playlist_ids, Playlist.where("event_id IN (?)",  current_user.event_ids), :id, :name
          =f.input :new_playlist_name, input_html: { class: 'form-control' }, placeholder: "Enter a new playlist name"
    .row.details
      .col-md-10
        %hr
        -if @video.status == 'draft'
          =f.submit "Publish video", class: "btn btn-warning top-15"
        - else
          =f.submit class: "btn btn-warning top-15"
        -if @video.id
          =link_to "Delete video", video_path(@video), method: :delete, data: {confirm: "Are you sure you want to delete this video?"}, class: "btn btn-default top-15"
        =link_to admin_path do
          %btn.btn.btn-default.top-15 Back to Admin page

app/views/videos/_nav.html.haml
.row
  .col-md-8.col-md-offset-2
    %h2.center Watch Ignite videos
    %p.center
      IgniteTalks.io contains Ignite videos from around the world.
      %span.hidden-sm.hidden-xs
        -if user_signed_in?
          = link_to "Add a new video", new_video_path
        / - else
        /   = link_to "Tell us", "https://docs.google.com/forms/d/1NrIlpRb_IvBl1zGw0LuVhipUxeVJE1r28UUglcFXYjQ/viewform", :target => "_blank"
        /   about a great Ignite video!
%hr

.row
  .col-xs-6.col-xs-offset-3
    %nav.navbar#video-nav
      %ul.nav.navbar-nav
        %li
          =link_to "Browse videos", videos_path
        %li
          =link_to "Watch playlists", playlists_path
        %li
          =link_to "Find videos by tags", tags_path
      

app/views/videos/_thumbnail.html.haml
/ Generate a thumbnail image containing viewing stats, which links to the video

=link_to video do
  %span.video_thumbnail
    / -if video.hd?
    /   =image_tag  "//img.youtube.com/vi/#{video.uid}/maxresdefault.jpg", :class => "thumb", :alt => truncate(video.title, length: 30)
    / - else
    =image_tag  "//img.youtube.com/vi/#{video.uid}/hqdefault.jpg", :class => "thumb", :alt => truncate(video.title, length: 30)
    %span{:class => rating_class}
      %i.fa.fa-youtube-play.right-5
      #{number_with_delimiter(video.views, :delimiter => ',')}
      %span.right-5
        %i.fa.fa-thumbs-up.right-5
        #{number_with_delimiter(video.likes, :delimiter => ',')}
      %span.right-5
        %i.fa.fa-thumbs-down.right-5
        #{number_with_delimiter(video.dislikes, :delimiter => ',')}
%p.title.truncate= link_to(video.title, video)
%p.subtitle.truncate
  -if not video.speaker_name.blank?
    - if not video.speaker_url.blank?
      = link_to video.speaker_name, video.speaker_url
    - else
      = video.speaker_name
  at
  = link_to video.event.name, event_page_path(video.event)

app/views/videos/_thumbnail_without_event_name.html.haml
/ Generate a thumbnail image containing viewing stats, which links to the video

=link_to video do
  %span.video_thumbnail
    / -if video.hd?
    /   =image_tag  "//img.youtube.com/vi/#{video.uid}/maxresdefault.jpg", :class => "thumb", :alt => truncate(video.title, length: 30)
    / - else
    =image_tag  "//img.youtube.com/vi/#{video.uid}/hqdefault.jpg", :class => "thumb", :alt => truncate(video.title, length: 30)
    %span{:class => rating_class}
      %i.fa.fa-youtube-play.right-5
      #{number_with_delimiter(video.views, :delimiter => ',')}
      %span.right-5
        %i.fa.fa-thumbs-up.right-5
        #{number_with_delimiter(video.likes, :delimiter => ',')}
      %span.right-5
        %i.fa.fa-thumbs-down.right-5
        #{number_with_delimiter(video.dislikes, :delimiter => ',')}
%p.title.truncate= link_to video.title, video
%p.subtitle.truncate
  -if not video.speaker_name.blank?
    - if not video.speaker_url.blank?
      = link_to video.speaker_name, video.speaker_url
    - else
      = video.speaker_name

app/views/videos/edit.html.haml
.container.top-150
  .row
    .col-md-8.col-md-offset-2
      %h3.left-15 Edit video
      .embed-container
        =embed(@video.uid)

  .row 
    .col-md-8.col-md-offset-2
      .panel
        .panel-body
          = render 'form'

/ Disable the YouTube retrieve button in Edit mode
:javascript
  $(document).ready(function() {
    $(".details").show();
    $("#btnYouTubeRetrieve").addClass("disabled");
  });

app/views/videos/index.html.haml
.container-fluid
  = render 'nav'
  .row.top-50
    .col-md-4.col-sm-12.col-xs-12
      = form_tag videos_path, class: "form-inline", method: :get do
        .input-group
          = text_field_tag :query, params[:query], class: "form-control", id: "search", autocomplete: "off", placeholder: "Enter a keyword to search for an Ignite video"
          .input-group-btn
            - if params[:query].present?
              = link_to videos_path, class: "btn btn-default" do
                %i.fa.fa-times
            = submit_tag "Search", class: "btn btn-default"
    .col-md-8.right.hidden-sm.hidden-xs
      =link_to videos_path do
        %span.btn.btn-default.tags#clear-filter
          %i.fa.fa-times
          clear
      =link_to videos_path(sort: "views") do
        %span.btn.btn-default.tags{:id => "tag_views"}
          %i.fa.fa-youtube-play
          = "views"
      =link_to videos_path(sort: "likes") do
        %span.btn.btn-default.tags{:id => "tag_likes"}
          %i.fa.fa-thumbs-o-up
          = "likes"
    
  .row.top-50
    / .row.paginate
    /   = will_paginate @videos, renderer: BootstrapPagination::Rails
    -@videos.each_slice(4) do |vids|
      .row.top-15
        -vids.each do |video|
          .col-md-3.video_thumbnail
            %span= thumbnail(video, 'video_rating_small', 60)
  .row.paginate
    = will_paginate @videos, renderer: BootstrapPagination::Rails

app/views/videos/new.html.haml
.container.top-150
  .row 
    .col-md-8.col-md-offset-2
      .panel
        .panel-body
          = render 'form'

/ Enable the YouTube retrieve button when there's a URL to test
:javascript
  $(document).ready(function() {
    $('[data-toggle="tooltip"]').tooltip();
    $("#btnYouTubeRetrieve").addClass("disabled");
    if ($("#video_url").val() == '') {
      $(".details").hide();
    } else {
      $(".details").show();
    }
  });

app/views/videos/show.html.haml
.container.top-150
  - if can? :update, @video
    .row.right
      .col-md-8.user
      = link_to edit_video_path(@video), class: "light btn-edit" do
        %i.fa.fa-pencil-square-o
      = link_to video_path(@video), method: :delete, class: "light btn-delete", data: {confirm: "Are you sure you want to delete this video?"} do
        %i.fa.fa-times
  .row 
    .col-md-12.col-lg-10.col-lg-offset-1
      %h3
        -if @video.R18?
          =@video.title + " (18+)"
        - else
          = @video.title
      %p.title
        -if not @video.speaker_name.blank?
          - if not @video.speaker_url.blank?
            by
            = link_to @video.speaker_name, @video.speaker_url
          - else
            = "by #{@video.speaker_name}"
      %p.subtitle
        Filmed at
        = link_to @video.event.name, event_page_path(@video.event)
      .embed-container
        =embed(@video.uid)
      .stats.right
        %i.fa.fa-youtube-play
        %span.right-15= number_with_delimiter(@video.views, :delimiter => ',')
        %i.fa.fa-thumbs-o-up
        %span.right-15= number_with_delimiter(@video.likes, :delimiter => ',')
        %i.fa.fa-thumbs-o-down.left-5
        = number_with_delimiter(@video.dislikes, :delimiter => ',')

    / -if not @video.tags.empty?
    /   .row 
    /     .col-md-8
    /       .tags.left-15
    /         %i.fa.fa-tag
    /         %span= @video.tags.map(&:name).join(", ").titleize

    -if not @video.description.blank?
      .row 
        .col-md-10.col-md-offset-1
          %p.top-50.left-15= @video.description

  -if @related_videos.count > 0
    .row.related
      .col-md-12
        %h4 Related Videos
    .row
      - @related_videos.each do |related_video|
        .col-md-3
          = thumbnail(related_video, 'video_rating_small', 35)

  .row
    .col-md-12
      %h4 More Ignite videos
  .row
    - @more_videos.each do |more_video|
      .col-md-3
        = thumbnail(more_video, 'video_rating_small', 35)

          