config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :events do
    resources :videos
    resources :playlists
  end

  resources :contacts, only: [:new, :create]
  resources :videos
  resources :upcomings
  resources :roles
  resources :tags
  resources :playlists

  post 'videos' => 'videos#create'

  get '/admin', to: 'admin#index', as: :admin #=> admin_path
  get '/contact', to: 'content#contact', as: :contact #=> contact_path
  get '/feedback', to: 'content#contact', as: :feedback #=> feedback_path
  get '/stats', to: 'content#stats', as: :stats_page
  get '/about', to: 'content#about', as: :about #=> about_path
  get '/start', to: 'content#start', as: :start #=> start_path
  get '/howto', to: 'content#howto', as: :howto #=> howto_path
  get '/ignites', to: 'events#index', as: :events_page
  get '/:id', to: 'events#show', as: :event_page

  root to: "content#home"

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :name, :city
  validates_uniqueness_of :name
  validates :url, :url => {:allow_blank => true}
  has_many :videos, dependent: :destroy
  has_many :upcomings, dependent: :destroy
  has_and_belongs_to_many :users
  has_many :playlists, dependent: :destroy
  searchkick

  # Geocoding
  geocoded_by :city
  reverse_geocoded_by :latitude, :longitude do |obj, results|
    if geo = results.first
      # obj.city = geo.city
      obj.state = geo.state
      obj.country = geo.country
    end
  end
  after_validation :geocode, if: :city_changed?
  after_validation :reverse_geocode, if: :city_changed?

  # Friendly IDs in the URL
  extend FriendlyId
  friendly_id :name, :use => :slugged

  def should_generate_new_friendly_id?
    name_changed?
  end

  def remove_ignite
    name.sub("Ignite ","")
  end

end

app/controllers/event_controller.rb
class EventController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_event, only: [:show, :edit, :update, :destroy]
  
  def index
    @events = Event.all
  end

  def show
  end

  def edit
  end

  def create
  end

  def destroy
  end

  private

  def event_params
    params.require(:event).permit(:name, :city, :url)
  end

  def find_event
    @event = event.find(params[:id])
    # @event = event.friendly.find(params[:id])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource :find_by => :slug, except: [:index, :show]
  before_action :find_event, only: [:show, :edit, :update, :destroy]
  layout 'no_footer', :only => [:new, :edit]
  
  # rescue_from ActiveRecord::RecordNotFound do
  #   flash[:notice] = "Sorry, that event does not exist"
  #   redirect_to action: :index
  # end

  def index
    @geojson = Array.new #TODO - hardcode the IgniteTalks event to the JSON so it's always shown
    @allEvents = Event.all.order(:name)
    if params[:bbox].present?
      #Find events which fall within the current map extent
      bbox = params[:bbox].split(",").map(&:to_f)
      @events = Event.within_bounding_box(bbox).order(:name)
    elsif params[:id].present?
      # This path is called when the user chooses an Ignite from the dropdown on the Events page. In
      # this case, open that event's homepage (and break out of the rest of this function)
      @event = Event.find(params[:id])
      redirect_to @event
      return
    elsif params[:name].present?
      # Check whether this event already exists. This is called when creating a new video, to save the
      # user from wasting time entering details about an existing video.
      # eg: http://localhost:3000/events.json?name=ignite+sydney
      @events = Event.where(:name => params[:name])
    else
      @events = Event.all.order(:name)  
    end
    # Make a JSON object from the events, to add to the map
    @geojson += @events.collect do |event|
      {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [event.longitude, event.latitude]
        },
        properties: {
          type: "event",
          id: event.id,
          name: event.name,
          city: event.city,
          country: event.country,
          url: event.slug
        }
      }
    end
    respond_to do |format|
      format.html
      if params["draw"].present?
        # Format the response for the DataTables plugin on the Admin page
        format.json { render json: EventDatatable.new(view_context, { user: current_user, role: current_user.role }) }
      else
        # Format the response for the map
        format.json { render json: @geojson }
      end
    end
  end

  def show
    # Sort any playlists in reverse numeric order. The regex is to account for letters and numbers, eg Ignite Sydney 10 should come after Ignite Sydney 9
    # (Except, the order is reversed so that the most recent playlists are shown at the top)
    @playlists = @event.playlists.where("video_count > 0").sort_by { |key| key.name.split(/(\d+)/).map { |v| v =~ /\d/ ? v.to_i : v } }.reverse!
    if @playlists.count > 0
      # Don't show the same videos in a playlist and in the non-playlist section
      @videos = @event.videos.where("status = 'published'")
      @playlists.each do |playlist|
        @videos -= playlist.videos.where("status = 'published'")
      end
      @videos = @videos.paginate(:page => params[:page], :per_page => 16)
    else
      @videos = @event.videos.where("status = 'published'").paginate(:page => params[:page], :per_page => 16)
    end
    @upcomings = @event.upcomings.where('date > ?', Date.yesterday)
    @og_title = @event.name + ' on IgniteTalks.io'
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.create(event_params)

    if @event.save
        flash[:notice] = "Event #{@event.name} added successfully."
        redirect_to admin_path
      else
        flash[:notice] = @event.errors.full_messages.to_sentence
        render 'new', layout: 'no_footer'
      end    
  end

  def update
    if @event.update(event_params)
      redirect_to admin_path
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    flash[:notice] = "Event #{@event.name} deleted successfully."
    redirect_to admin_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :city, :country, :url, :status, :twitter_name)
  end

  def find_event
    @event = Event.friendly.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= simple_form_for(@event, html: { class: 'form' })  do |f|
  .form-group
    =f.input :name,  input_html: { class: 'form-control' }, placeholder: "Enter the event's full name (eg Ignite Seattle)"
    =f.input :city, input_html: { class: 'form-control' }, placeholder: "Enter the city (eg Seattle)"
    / =f.input :country, input_html: { class: 'form-control' }, placeholder: "Enter the country (eg USA)"
    =f.input :url, input_html: { class: 'form-control' }, placeholder: "Enter the event's homepage (eg http://www.igniteseattle.com)"
    =f.input :twitter_name, input_html: { class: 'form-control' }, placeholder: "Enter the Twitter name (eg igniteseattle)"
  =f.submit class: "btn btn-warning"
  =link_to root_path do
    %btn.btn.btn-default Cancel

app/views/events/edit.html.haml
.container.top-150
  .row 
    .col-md-8.col-md-offset-2
      .panel
        .panel-heading Edit event
        .panel-body
          = render 'form'
          %hr
            %button.btn
              = link_to "Back to event page", event_path
            - if can? :destroy, @event
              %button.btn
                = link_to "Delete event", event_path(@event), method: :delete, data: {confirm: "Are you sure you want to delete this event?"}
            %button.btn
              = link_to "Back to Admin page", admin_path

app/views/events/index.html.haml
.container
  .row
    #map.col-md-12

  .row.top-15
    .col-md-4.col-md-offset-4
      .form-group
        //=select_tag "selectAllEvents", options_from_collection_for_select(@allEvents, "id", "name".gsub("Ignite ","")), prompt: "Choose an Ignite, or search on the map", class: "form-control"
        =select_tag "selectAllEvents", options_for_select(@allEvents.collect{ |u| [u.name.gsub("Ignite ",""), u.id] }), prompt: "Choose an Ignite from the list, or search on the map", class: "form-control"
  .row
    #results.col-md-12.col-sm-12.col-xs-12

  / -if not user_signed_in?
  /   .row.top-50.hidden-sm.hidden-xs
  /     .col-md-12
  /       %p
  /         Don't see your Ignite listed?
  /         / =link_to "Tell us about it!", new_event_path
  /         =link_to "Tell us about it!", "https://docs.google.com/forms/d/1yD7jEXHcws3qFRup91G-mM9YOKvDlfOO3vaJw2GnGaU/viewform", :target => "_blank"

app/views/events/new.html.haml
.container.top-150
  .row 
    .col-md-8.col-md-offset-2
      .panel
        %h1.left-15 Add a new Ignite
        .panel-body
          = render 'form'
          %hr
          %button.btn
            = link_to "Back to Admin page", admin_path

app/views/events/show.html.haml
.container-fluid.event
  - if can? :update, @event
    .user.right
      = link_to edit_event_path(@event), class: "light btn-edit" do
        %i.fa.fa-pencil-square-o
      - if can? :destroy, @event
        = link_to event_path(@event), method: :delete, class: "light btn-delete", data: {confirm: "Are you sure you want to delete this event?"} do
          %i.fa.fa-times
  .row
    .col-md-4.col-md-offset-2
      %h1= @event.name
      - if not @event.state.blank?
        %p= "#{@event.city}, #{@event.state}, #{@event.country}"
      - else
        %p= "#{@event.city}, #{@event.country}"
    .col-md-6.top-25
      - if not @event.url.blank?
        = link_to @event.url, :target => "_blank" do
          %i.fa.fa-desktop
          =@event.url
          %br
      - if not @event.twitter_name.blank?
        = link_to "https://www.twitter.com/#{@event.twitter_name}", :target => "_blank" do
          %i.fa.fa-twitter
          =@event.twitter_name
          %br
      -if @upcomings.count > 0
        %i.fa.fa-calendar
        Next event:
        = @upcomings.first.name
        = "(#{@upcomings.first.date})"
        %br

  - if @playlists.count > 0 and (not params["page"] or params["page"] == "1")
    .row.top-50
      %h4.left-15
        Playlists from
        =@event.name

    -@playlists.each do |playlist|
      .row.top-15
        .col-md-12
          %h4= link_to playlist.name, playlist
        -playlist.videos.where("status = 'published'").order("RANDOM()").limit(4).each_slice(4) do |vids|
          - vids.each do |video|
            .col-md-3.playlist_thumbnail
              %span= thumbnail_without_event_name(video, 'video_rating_small', 30)
        -if playlist.videos.count > 4
          %p.left-15=  link_to "View all videos from #{playlist.name}", playlist

  - if not @videos.empty?
    .row.top-50
      %h4.left-15
        Videos recorded at
        =@event.name
    .row.paginate
      = will_paginate @videos, renderer: BootstrapPagination::Rails
    - @videos.each_slice(4) do |vids|
      .row
        .col-md-12
        - vids.each do |video|
          .col-md-3.col-sm-12.col-xs-12
            = thumbnail_without_event_name(video, 'video_rating_small', 30)
    .row.paginate
      = will_paginate @videos, renderer: BootstrapPagination::Rails

      