config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :events do
    resources :videos
    resources :playlists
  end

  resources :contacts, only: [:new, :create]
  resources :videos
  resources :upcomings
  resources :roles
  resources :tags
  resources :playlists

  post 'videos' => 'videos#create'

  get '/admin', to: 'admin#index', as: :admin #=> admin_path
  get '/contact', to: 'content#contact', as: :contact #=> contact_path
  get '/feedback', to: 'content#contact', as: :feedback #=> feedback_path
  get '/stats', to: 'content#stats', as: :stats_page
  get '/about', to: 'content#about', as: :about #=> about_path
  get '/start', to: 'content#start', as: :start #=> start_path
  get '/howto', to: 'content#howto', as: :howto #=> howto_path
  get '/ignites', to: 'events#index', as: :events_page
  get '/:id', to: 'events#show', as: :event_page

  root to: "content#home"

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :videos
  validates_presence_of :name
  validates_uniqueness_of :name

  # Friendly IDs in the URL
  extend FriendlyId
  friendly_id :name, :use => :slugged

  def should_generate_new_friendly_id?
    name_changed?
  end
  
  # Force all tags to lowercase to prevent duplication
  before_save { |tag| tag.name = tag.name.downcase }

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource :find_by => :slug, except: [:index, :show]
  before_action :find_tag, only: [:show, :edit, :update, :destroy, :update_stats]
  layout 'no_footer', :only => [:new, :edit]

  def index
    if params[:name].present?
      # Check whether this tag already exists
      # eg: http://localhost:3000/tags.json?name=technology
      @tags = Tag.where(:name => params[:name]).order('name ASC').paginate(:page => params[:page], :per_page => 60)
    else
      @tags = Tag.where("video_count > 0").order('name ASC').paginate(:page => params[:page], :per_page => 60)
    end

    # Respond as JSON, so that this function can be called via AJAX to determine whether a video
    # already exists when creating a new video via http://localhost:3000/videos/new
    respond_to do |format|
      format.html
      if params["draw"].present?
        # Format the response for the DataTables plugin on the Admin page
        format.json { render json: TagDatatable.new(view_context, { user: current_user, role: current_user.role }) }
      else
        format.json { render json: @tags }
      end
    end

  end

  def new
    @tag = Tag.new
  end

  def show
    @videos = @tag.videos.order(:title).paginate(:page => params[:page], :per_page => 16)
  end

  def edit
  end

  def create
    # @tag = current_user.tags.build(tag_params)
    @tag = Tag.create(tag_params)
    @tag.user = current_user
    if @tag.save
        flash[:notice] = "tag #{@tag.name} added successfully."
        redirect_to admin_path
      else
        flash[:notice] = @tag.errors.full_messages.to_sentence
        render 'new', layout: 'no_footer'
      end    
  end

  def update
    if @tag.update(tag_params)
      if current_user.curator?
        redirect_to admin_path
      else
        redirect_to @tag
      end
    else
      render 'edit'
    end
  end


  def destroy
    @tag.destroy
    flash[:notice] = "Tag #{@tag.name} deleted successfully."
    redirect_to admin_path
  end

private

  def tag_params
    params.require(:tag).permit(:name, :user_id)
  end

    def find_tag
    @tag = Tag.friendly.find(params[:id])
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
= simple_form_for(@tag, html: { class: 'form' })  do |f|
  .form-group
    =f.input :name,  input_html: { class: 'form-control' }, placeholder: "Tag name"
  =f.submit class: "btn btn-warning"
  =link_to root_path do
    %btn.btn.btn-default Cancel

app/views/tags/edit.html.haml
.container.top-150
  .row 
    .col-md-8.col-md-offset-2
      .panel
        %h1.left-15 Edit Tag
        .panel-body
          = render 'form'
          %hr
          %button.btn
            = link_to "Back to Admin page", admin_path

app/views/tags/index.html.haml
.container
  =render "videos/nav"
  .row.top-50
  - @tags.each_slice(6) do |tags|
    .row.top-15
      -tags.each do |tag|
        .col-md-2
          %strong
            = link_to tag.name.upcase, tag
          %br
          =pluralize tag.video_count, "video"
          - if can? :update, tag
            = link_to edit_tag_path(tag), class: "light btn-edit" do
              %i.fa.fa-pencil-square-o
            = link_to tag_path(tag), method: :delete, class: "light btn-delete", data: {confirm: "Are you sure you want to delete this tag?"} do
              %i.fa.fa-times
  .row.paginate
    = will_paginate @tags, renderer: BootstrapPagination::Rails

app/views/tags/new.html.haml
.container.top-150
  .row 
    .col-md-8.col-md-offset-2
      .panel
        %h1.left-15 Add a new Tag
        .panel-body
          = render 'form'
          %hr
          %button.btn
            = link_to "Back to Admin page", admin_path

app/views/tags/show.html.haml
.container-fluid.top-150
  = render 'videos/nav'
  - if can? :update, @tag
    .row.right
      .col-md-8.user
      = link_to edit_tag_path(@tag), class: "light btn-edit" do
        %i.fa.fa-pencil-square-o
      = link_to tag_path(@tag), method: :delete, class: "light btn-delete", data: {confirm: "Are you sure you want to delete this tag?"} do
        %i.fa.fa-times
  .row.paginate
    = will_paginate @videos, renderer: BootstrapPagination::Rails
  .row 
    .col-md-12.col-lg-10.col-lg-offset-1
      %h4
        Videos tagged as
        =@tag.name
      - @videos.each_slice(4) do |vids|
        .row.top-15
          -vids.each do |video|
            .col-md-3.video_thumbnail
              %span= thumbnail(video, 'video_rating_small', 30)
  .row.paginate
    = will_paginate @videos, renderer: BootstrapPagination::Rails

          